#! /bin/sh
COLOR_BLACK="\\033[0;30m" # Black - Regular
COLOR_RED="\\033[0;31m" # Red
COLOR_GREEN="\\033[0;32m" # Green
COLOR_YELLOW="\\033[0;33m" # Yellow
COLOR_BLUE="\\033[0;34m" # Blue
COLOR_PURPLE="\\033[0;35m" # Purple
COLOR_CYAN="\\033[0;36m" # Cyan
COLOR_WHITE="\\033[0;37m" # White

# create a bin dir in brunch
echo "\n""$COLOR_YELLOW""-------------------------""$COLOR_WHITE""\n"

cd ../brunch

echo "Starting the custom builder"

echo "Cleaning brunch/android/"
rm -rf android/
mkdir android/

echo "Updating brunch/android/"

# copy phonegap.js in the vendor folder
cp -rf src/.android/ src/
echo "\n""$COLOR_YELLOW""-------------------------""$COLOR_WHITE""\n"
brunch build .
echo "\n""$COLOR_YELLOW""-------------------------""$COLOR_WHITE""\n"

# copy compiled css and js and assets
cp -r build/web/* android/

# get index.html content, change the paths, put it in a new file
echo "Changing paths of index.html"
sed -e 's/build\/web\///g' index.html > android/index.html

# copy the web version of phonegap in the folder
cp -rf src/.web/ src/
echo "\n""$COLOR_YELLOW""-------------------------""$COLOR_WHITE""\n"
brunch build .

cd ../android